# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

commands:
  build:
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy-test:
    steps:
      - run: npm run deploy-test
  deploy-prod:
    steps:
      - run: npm run deploy-prod

jobs:
  build:
    executor: aws-cli/default
    steps:
      - build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy-test:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - attach_workspace:
          at: .
      - deploy-test

  deploy-prod:
    machine:
      image: ubuntu-2204:2022.10.1
    steps:
      - attach_workspace:
          at: .
      - deploy-prod

workflows:
  build:
    jobs:
      - build:
        environment:
          REACT_APP_MEALS_API_ENDPOINT=https://c1zkkudewi.execute-api.eu-west-1.amazonaws.com/prod